GenC.Web/Controllers/ConsultaController.cs
using GenC.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GenC.Web.Controllers
{
    public class ConsultaController:baseController
    {
        public ActionResult Index()
        {
            if (!SessionAuth())
            {
                return RedirectToAction("Index", "Login");
            }

            int UsuariosId = Current_user();
            var agendamentos = db.Agendamentos.Where(d => d.Usuarios.Id == UsuariosId).OrderByDescending(d => d.DtAgendamento).ToList();
            ViewBag.ChaveGoogle = GoogleMapsKey;

            return View(agendamentos);
        }

        [HttpPost]
        public ActionResult cadastrarEvento(Agendamentos agendamento)
        {
            if (!SessionAuth())
                return Json(new { mensagem = "Conectar-se novamente" });

            if (!ModelState.IsValid)
                return Json(agendamento);

            int usuarioId = Current_user();

            var mensagemRetorno = "";

            try
            {
                Usuarios usuarioLogado = db.Usuarios.Where(u => u.Id == usuarioId).FirstOrDefault();
                agendamento.IdUsuario = usuarioLogado.Id;
                agendamento.Usuarios = usuarioLogado;
                db.Agendamentos.Add(agendamento);
                db.SaveChanges();
                mensagemRetorno = "Evento registrado";
            }
            catch (Exception ex)
            {
                mensagemRetorno = ex.Message.ToString();
            }

            return Json(new { mensagem = mensagemRetorno });

        }
        public ActionResult buscarEventos(string pesquisa)
        {
            if (!SessionAuth())
            {
                return RedirectToAction("Index", "Login");
            }

            int UsuariosId = Current_user();

            if (!String.IsNullOrEmpty(pesquisa))
            {
                var devices = db.Agendamentos.Where(d => d.Usuarios.Id == UsuariosId && d.Titulo.Contains(pesquisa) || d.Usuarios.Id == UsuariosId && d.Descricao.Contains(pesquisa));
                return Json(devices.ToList(), JsonRequestBehavior.AllowGet);
            }

            else
            {
                var devices = db.Agendamentos.Where(d => d.Usuarios.Id == UsuariosId);
                return Json(devices.ToList(), JsonRequestBehavior.AllowGet);
            }


        }
    }
}

GenC.Web/Controllers/UsuariosController.cs
using GenC.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GenC.Web.Controllers
{
    public class UsuariosController: baseController
    {
        public ActionResult Create()
        {
            ViewBag.ChaveGoogle = GoogleMapsKey;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Usuarios Usuarios)
        {

            if (ModelState.IsValid)
            {
                var existeUsuario = db.Usuarios.Any(u => u.Email == Usuarios.Email || u.CPF == Usuarios.CPF);
                if (!existeUsuario)
                {
                    Usuarios.Senha = ComputeHash(Usuarios.Senha, null);

                    db.Usuarios.Add(Usuarios);
                    db.SaveChanges();
                    return RedirectToAction("Index", "Login");
                }                
            }

            return View(Usuarios);
        }
    }
}

GenC.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.20/r-2.2.3/datatables.min.css" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Agendão</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div id="loader" class="valign-wrapper">
        <div class="preloader-wrapper big active">
            <div class="spinner-layer spinner-blue-only">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div><div class="gap-patch">
                    <div class="circle"></div>
                </div><div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
    </div>
    @Html.Partial("_Nav")

    <div class="container">


        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/main")
    @Scripts.Render("~/bundles/inputmask")
    @Scripts.Render("~/bundles/materialize")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.20/r-2.2.3/datatables.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

GenC.Web/Views/Shared/_Nav.cshtml
@{
    int Id = 0;
    try
    {
        Id = Convert.ToInt32(Request.Cookies["Id"].Value.ToString());
    }
    catch
    {
        Id = 0;
    }

}
@if (Id != 0)
{
    <div class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <a href="@Url.Action("Index", "Consulta")" class="brand-logo center">
                    <i class="material-icons left">home</i>
                    Home
                </a>
                <ul id="nav-mobile" class="right">
                    <li><a href="@Url.Action("Index", "Consulta")"><i class="material-icons">date_range</i></a></li>
                    <li><a href="@Url.Action("Logout", "Login")"><i class="material-icons">person_pin</i></a></li>
                </ul>
            </div>
        </nav>
    </div>
}
else
{

    <div class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <a href="@Url.Action("Index", "Consulta")" class="brand-logo center">
                    <i class="material-icons left">ome</i>
                    Home
                </a>
                <ul id="nav-mobile" class="right">
                    <li><a href="@Url.Action("Create", "Usuarios")"><i class="material-icons">person_add</i></a></li>
                    <li><a href="@Url.Action("Index", "Login")"><i class="material-icons">account_circle</i></a></li>
                </ul>
            </div>
        </nav>
    </div>
}